// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package WorldStateTopic;

// <auto-generated>
//
// Generated from file `WorldState.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _WorldStateOperations
{
    long getUpdateID(Ice.Current __current);

    Ball getBallPosition(Ice.Current __current);

    Robot getYellowRobot(Ice.Current __current);

    Robot getBlueRobot(Ice.Current __current);

    int getPitch(Ice.Current __current);

    int getShootingDirection(Ice.Current __current);

    int getTeamColour(Ice.Current __current);
}
