// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package WorldStateTopic;

// <auto-generated>
//
// Generated from file `WorldState.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _WorldStateOperationsNC
{
    long getUpdateID();

    Ball getBallPosition();

    Robot getYellowRobot();

    Robot getBlueRobot();

    int getPitch();

    int getShootingDirection();

    int getTeamColour();
}
