// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package WorldStateTopic;

// <auto-generated>
//
// Generated from file `WorldState.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _WorldStateDel extends Ice._ObjectDel
{
    long getUpdateID(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    Ball getBallPosition(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    Robot getYellowRobot(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    Robot getBlueRobot(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getPitch(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getShootingDirection(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getTeamColour(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
