// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package WorldStateTopic;

// <auto-generated>
//
// Generated from file `WorldState.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class Ball implements java.lang.Cloneable, java.io.Serializable
{
    public Position pos;

    public Ball()
    {
    }

    public Ball(Position pos)
    {
        this.pos = pos;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Ball _r = null;
        try
        {
            _r = (Ball)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(pos != _r.pos)
            {
                if(pos == null || _r.pos == null || !pos.equals(_r.pos))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(pos != null)
        {
            __h = 5 * __h + pos.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        pos.__write(__os);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        pos = new Position();
        pos.__read(__is);
    }
}
