// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package ControlTopic;

// <auto-generated>
//
// Generated from file `Control.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _ControlOperations
{
    void connect(Ice.Current __current);

    void disconnect(Ice.Current __current);

    void setLeftMotorSpeed(int speed, Ice.Current __current);

    void setRightMotorSpeed(int speed, Ice.Current __current);

    void driveForward(Ice.Current __current);

    void driveForwardSpeed(int speed, Ice.Current __current);

    void driveBackward(Ice.Current __current);

    void driveBackwardSpeed(int speed, Ice.Current __current);

    void driveStop(Ice.Current __current);

    void turnLeft(Ice.Current __current);

    void turnLeftSpeed(int speed, Ice.Current __current);

    void turnRight(Ice.Current __current);

    void turnRightSpeed(int speed, Ice.Current __current);

    void kick(Ice.Current __current);

    void sendInt(int i, Ice.Current __current);

    void shutDownRobot(Ice.Current __current);

    boolean isMoving(Ice.Current __current);
}
